# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PHQ9Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('little_interest', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Little interest or pleasure in doing things?')),
                ('depression', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Feeling down, depressed, or hopeless?')),
                ('sleep_issues', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Trouble falling or staying asleep, or sleeping too much?')),
                ('lethargy', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Feeling tired or having little energy?')),
                ('appetite_issues', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Poor appetite or overeating?')),
                ('shame', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Feeling bad about yourself -- or that you are a failure or have let yourself or your family down?')),
                ('concentration_issues', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Trouble concentrating on things, such as reading the newspaper or watching television?')),
                ('activity_change', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Moving or speaking so slowly that other people could have noticied? Or the opposite -- being so fidgety or restless that you have been moving around a lot more than usual?')),
                ('suicidal_thoughts', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Thoughts that you would be better off dead, or of hurting yourself in some way?')),
                ('depression_severity', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
